// StatusCode generated by goctl. DO NOT EDIT!

package dal

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videosFieldNames          = builder.RawFieldNames(&Videos{})
	videosRows                = strings.Join(videosFieldNames, ",")
	videosRowsExpectAutoSet   = strings.Join(stringx.Remove(videosFieldNames, "`create_time`", "`update_time`"), ",")
	videosRowsWithPlaceHolder = strings.Join(stringx.Remove(videosFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheVideosIdPrefix = "cache:videos:id:"
)

type (
	videosModel interface {
		Insert(ctx context.Context, data *Videos) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Videos, error)
		Update(ctx context.Context, data *Videos) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVideosModel struct {
		sqlc.CachedConn
		table string
	}

	Videos struct {
		Id            int64     `db:"id"`
		UserId        int64     `db:"user_id"`
		PlayUrl       string    `db:"play_url"`
		CoverUrl      string    `db:"cover_url"`
		FavoriteCount int64     `db:"favorite_count"`
		CommentCount  int64     `db:"comment_count"`
		Title         string    `db:"title"`
		CreatedAt     time.Time `db:"created_at"`
	}
)

func newVideosModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultVideosModel {
	return &defaultVideosModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`videos`",
	}
}

func (m *defaultVideosModel) Insert(ctx context.Context, data *Videos) (sql.Result, error) {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, videosRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.PlayUrl, data.CoverUrl, data.FavoriteCount, data.CommentCount, data.Title, data.CreatedAt)
	}, videosIdKey)
	return ret, err
}

func (m *defaultVideosModel) FindOne(ctx context.Context, id int64) (*Videos, error) {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, id)
	var resp Videos
	err := m.QueryRowCtx(ctx, &resp, videosIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videosRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideosModel) Update(ctx context.Context, data *Videos) error {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videosRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.PlayUrl, data.CoverUrl, data.FavoriteCount, data.CommentCount, data.Title, data.CreatedAt, data.Id)
	}, videosIdKey)
	return err
}

func (m *defaultVideosModel) Delete(ctx context.Context, id int64) error {
	videosIdKey := fmt.Sprintf("%s%v", cacheVideosIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, videosIdKey)
	return err
}

func (m *defaultVideosModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheVideosIdPrefix, primary)
}

func (m *defaultVideosModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", videosRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVideosModel) tableName() string {
	return m.table
}
