// Code generated by goctl. DO NOT EDIT.
package types

type FavoriteReq struct {
	UserId     string `form:"userid"`      // 用户id
	Token      string `form:"token"`       // 用户token
	VideoId    string `form:"video_id"`    // 视频id
	ActionType int64  `form:"action_type"` //1-点赞，2-取消点赞
}

type FavoriteResp struct {
	Code int64   `json:"status_code"`
	Msg  *string `json:"status_msg"`
}

type FavoriteListReq struct {
	UserId string `form:"userid"` // 用户id
	Token  string `form:"token"`  // 用户token
}

type FavoriteListResp struct {
	StatusCode string  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  *string `json:"status_msg"`  // 返回状态描述
	VideoList  []Video `json:"video_list"`  // 用户点赞视频列表
}

type Video struct {
	Author        User   `json:"author"`         // 视频作者信息
	CommentCount  int64  `json:"comment_count"`  // 视频的评论总数
	CoverURL      string `json:"cover_url"`      // 视频封面地址
	FavoriteCount int64  `json:"favorite_count"` // 视频的点赞总数
	ID            int64  `json:"id"`             // 视频唯一标识
	IsFavorite    bool   `json:"is_favorite"`    // true-已点赞，false-未点赞
	PlayURL       string `json:"play_url"`       // 视频播放地址
	Title         string `json:"title"`          // 视频标题
}

type User struct {
	FollowCount   int64  `json:"follow_count"`   // 关注总数
	FollowerCount int64  `json:"follower_count"` // 粉丝总数
	ID            int64  `json:"id"`             // 用户id
	IsFollow      bool   `json:"is_follow"`      // true-已关注，false-未关注
	Name          string `json:"name"`           // 用户名称
}
