// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sixwaaaay/shauser/internal/config"
	"github.com/sixwaaaay/shauser/internal/data"
	"github.com/sixwaaaay/shauser/internal/logic"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewServer(conf *config.Config, db *gorm.DB) *WebApi {
	userQuery := data.NewUserQuery(db)
	followQuery := data.NewFollowQuery(db)
	getUserLogicOption := logic.GetUserLogicOption{
		Config:  conf,
		UserQ:   userQuery,
		FollowQ: followQuery,
	}
	getUserLogic := logic.NewGetUserLogic(getUserLogicOption)
	getUsersLogicOption := logic.GetUsersLogicOption{
		Config:  conf,
		UserQ:   userQuery,
		FollowQ: followQuery,
	}
	getUsersLogic := logic.NewGetUsersLogic(getUsersLogicOption)
	webApi := NewWebApi(getUserLogic, getUsersLogic)
	return webApi
}
